# Generated by Django 3.2 on 2022-03-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('name', models.CharField(max_length=64, verbose_name='Nome da moeda')),
                ('sigla', models.CharField(max_length=16, verbose_name='Sigla da moeda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('date_quote', models.DateField(verbose_name='Data da quotação')),
                ('value_coin', models.DecimalField(decimal_places=7, max_digits=10)),
                ('coin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.coin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
