# Generated by Django 3.2 on 2022-03-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quote_coin_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='coin_base',
            field=models.CharField(choices=[('USD', 'Usd'), ('BRL', 'Brl')], default='USD', max_length=3, verbose_name='Valor Base'),
        ),
    ]
