# Generated by Django 3.2 on 2022-03-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_quote_coin_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('rate_base', models.CharField(choices=[('USD', 'Usd'), ('BRL', 'Brl')], default='USD', max_length=3, verbose_name='Valor Base')),
                ('date', models.DateField(verbose_name='Data da quotação')),
                ('value', models.DecimalField(decimal_places=7, max_digits=10)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.coin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
